name: Run PR checks
run-name: Checks for PR#${{ github.event.pull_request.number }}

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  NODE_INSTALL_VERSION: 20.x
  PNPM_INSTALL_VERSION: 8

jobs:
  lint:
    name: Linter check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_INSTALL_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_INSTALL_VERSION }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run prettier
        run: pnpm lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_INSTALL_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_INSTALL_VERSION }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Run test
        run: pnpm test
      - name: Run build
        run: pnpm build
      - name: Link build artifacts to Pull Request
        uses: gavv/pull-request-artifacts@93f32f061d1fabdb41104db2493f2260c7db774f
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          comment-message: Generated artifacts for this PR
          comment-style: table
          artifacts: |
            build

  dependency-review:
    name: Check for security/license issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v3
